insert into estados (sigla, descricao, codigo) values ('AC','ACRE','12');
insert into estados (sigla, descricao, codigo) values ('AL','ALAGOAS','27');
insert into estados (sigla, descricao, codigo) values ('AM','AMAZONAS','13');
insert into estados (sigla, descricao, codigo) values ('AP','AMAPA','16');
insert into estados (sigla, descricao, codigo) values ('BA','BAHIA','29');
insert into estados (sigla, descricao, codigo) values ('CE','CEARA','23');
insert into estados (sigla, descricao, codigo) values ('DF','DISTRITO FEDERAL','53');
insert into estados (sigla, descricao, codigo) values ('ES','ESPIRITO SANTO','32');
insert into estados (sigla, descricao, codigo) values ('GO','GOIAS','52');
insert into estados (sigla, descricao, codigo) values ('MA','MARANHAO','21');
insert into estados (sigla, descricao, codigo) values ('MG','MINAS GERAIS','31');
insert into estados (sigla, descricao, codigo) values ('MS','MATO GROSSO DO SUL','50');
insert into estados (sigla, descricao, codigo) values ('MT','MATO GROSSO','51');
insert into estados (sigla, descricao, codigo) values ('PA','PARA','15');
insert into estados (sigla, descricao, codigo) values ('PB','PARAIBA','25');
insert into estados (sigla, descricao, codigo) values ('PE','PERNAMBUCO','26');
insert into estados (sigla, descricao, codigo) values ('PI','PIAUI','22');
insert into estados (sigla, descricao, codigo) values ('PR','PARANA','41');
insert into estados (sigla, descricao, codigo) values ('RJ','RIO DE JANEIRO','33');
insert into estados (sigla, descricao, codigo) values ('RN','RIO GRANDE DO NORTE','24');
insert into estados (sigla, descricao, codigo) values ('RO','RONDONIA','11');
insert into estados (sigla, descricao, codigo) values ('RR','RORAIMA','14');
insert into estados (sigla, descricao, codigo) values ('RS','RIO GRANDE DO SUL','43');
insert into estados (sigla, descricao, codigo) values ('SC','SANTA CATARINA','42');
insert into estados (sigla, descricao, codigo) values ('SE','SERGIPE','28');
insert into estados (sigla, descricao, codigo) values ('SP','SAO PAULO','35');
insert into estados (sigla, descricao, codigo) values ('TO','TOCANTIS','17');